// Manual SFTP deploy to SiteGround.
//
// Usage:
//   npm run deploy:prod              — build (production), upload to <prod-domain>
//   npm run deploy:dev               — build (dev configuration), upload to <dev-subdomain>
//
// Direct flags (without the npm aliases):
//   node scripts/deploy.mjs --env=prod         — same as deploy:prod (default)
//   node scripts/deploy.mjs --env=dev          — same as deploy:dev
//   ... --only=code                  — upload only the JS/HTML/CSS bundle (skip assets/)
//   ... --only=assets                — upload only dist/.../assets/ → <remote>/assets/
//   ... --only=all                   — same as default
//   ... --skip-build                 — skip ng build (use what's already in dist/)
//   ... --dry-run                    — list files, don't upload
//
// The --env flag picks which deploy creds + remote dir get used. Prod uses the
// unprefixed env vars (DEPLOY_HOST, DEPLOY_REMOTE_DIR, …); dev uses the
// DEV_-prefixed counterparts (DEV_DEPLOY_HOST, DEV_DEPLOY_REMOTE_DIR, …) so a
// single .env.local can hold both targets without conflict. The chosen env
// also drives the Angular build configuration: prod = production, dev = dev.
//
// Configuration: copy .env.local.example to .env.local and fill in. The
// .env.local file is gitignored and never committed. SFTP is the only
// supported transport — SiteGround supports it on port 18765 with the
// hosting account's SSH user.
//
// SPA fallback: writes .htaccess into the upload root so deep links
// (/products/<slug>, /admin/...) reload to /index.html on Apache. Only
// the `code` and `all` modes touch .htaccess; `assets` leaves it alone.

import dotenv from 'dotenv';
import { spawnSync } from 'node:child_process';
import { readdir, readFile, stat, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import SftpClient from 'ssh2-sftp-client';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..');
const LOCAL_DIR = path.join(REPO_ROOT, 'dist', 'poke-singles', 'browser');

// `.env.local` is gitignored and holds the deploy creds. dotenv/config
// would only pick up plain `.env` — point it explicitly here.
dotenv.config({ path: path.join(REPO_ROOT, '.env.local') });

const ARGS = process.argv.slice(2);
const FLAG_SET = new Set(ARGS);
const SKIP_BUILD = FLAG_SET.has('--skip-build');
const DRY_RUN = FLAG_SET.has('--dry-run');

const ENV_VALUES = new Set(['prod', 'dev']);
const envArg = ARGS.find((a) => a.startsWith('--env='));
const ENV = (envArg ? envArg.slice('--env='.length) : 'prod').toLowerCase();
if (!ENV_VALUES.has(ENV)) {
  console.error(
    `[deploy] invalid --env=${ENV}. Expected one of: ${[...ENV_VALUES].join(', ')}`
  );
  process.exit(1);
}
// Dev keys are prefixed with DEV_; prod keys are unprefixed. A single
// .env.local can hold both targets, picked by the --env flag at run-time.
const KEY_PREFIX = ENV === 'dev' ? 'DEV_' : '';
const NG_CONFIG = ENV === 'dev' ? 'dev' : 'production';

const ONLY_VALUES = new Set(['code', 'assets', 'all']);
const onlyArg = ARGS.find((a) => a.startsWith('--only='));
const ONLY = (onlyArg ? onlyArg.slice('--only='.length) : 'all').toLowerCase();
if (!ONLY_VALUES.has(ONLY)) {
  console.error(
    `[deploy] invalid --only=${ONLY}. Expected one of: ${[...ONLY_VALUES].join(', ')}`
  );
  process.exit(1);
}

const HTACCESS_BODY = `# SPA fallback: every URL not matching an existing file or
# directory rewrites to index.html so the Angular router takes
# over. Generated by scripts/deploy.mjs — do not edit on the
# server, it gets overwritten on each deploy.
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ index.html [L]
`;

function fail(msg) {
  console.error(`[deploy] ${msg}`);
  process.exit(1);
}

function getRequiredEnv(name) {
  const value = process.env[name];
  if (!value || value.trim() === '') {
    fail(`Missing ${name} in .env.local`);
  }
  return value.trim();
}

// Hard guard: refuse to deploy into the legacy OpenCart site, no matter what
// .env.local says. The current live store at poke-singles.com must NOT be
// overwritten by this Angular bundle until the cutover is explicitly planned.
// To deploy to the production poke-singles.com root, edit this list deliberately.
const BLOCKED_REMOTE_PATHS = [
  /(^|\/)poke-singles\.com\/public_html\/?$/i,
];

function assertRemoteAllowed(remoteDir) {
  for (const pattern of BLOCKED_REMOTE_PATHS) {
    if (pattern.test(remoteDir)) {
      fail(
        `Refusing to deploy to "${remoteDir}" — that path is on the blocklist ` +
          `(scripts/deploy.mjs BLOCKED_REMOTE_PATHS). The live OpenCart site at ` +
          `poke-singles.com is protected until cutover. Use a subdomain like ` +
          `new.poke-singles.com instead, or remove the entry from the blocklist if ` +
          `you really mean to overwrite the live site.`
      );
    }
  }
}

async function* walk(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      yield* walk(full);
    } else {
      yield full;
    }
  }
}

async function build() {
  if (SKIP_BUILD) {
    console.log('[deploy] --skip-build set, using existing dist/');
    return;
  }
  console.log(`[deploy] running ng build --configuration=${NG_CONFIG}…`);
  const result = spawnSync(
    'npx',
    ['ng', 'build', '--configuration', NG_CONFIG],
    {
      cwd: REPO_ROOT,
      stdio: 'inherit',
      shell: process.platform === 'win32'
    }
  );
  if (result.status !== 0) {
    fail('ng build failed');
  }
}

async function ensureLocalDir() {
  if (!existsSync(LOCAL_DIR)) {
    fail(`Build output not found at ${LOCAL_DIR}. Run with build, or remove --skip-build.`);
  }
  const s = await stat(LOCAL_DIR);
  if (!s.isDirectory()) {
    fail(`${LOCAL_DIR} is not a directory.`);
  }
}

async function writeHtaccess() {
  const target = path.join(LOCAL_DIR, '.htaccess');
  await writeFile(target, HTACCESS_BODY, 'utf8');
}

async function buildAuthOptions() {
  const host = getRequiredEnv(`${KEY_PREFIX}DEPLOY_HOST`);
  const port = Number(process.env[`${KEY_PREFIX}DEPLOY_PORT`] ?? 18765);
  const username = getRequiredEnv(`${KEY_PREFIX}DEPLOY_USER`);

  const keyPath = process.env[`${KEY_PREFIX}DEPLOY_PRIVATE_KEY_PATH`]?.trim();
  if (keyPath) {
    const privateKey = await readFile(keyPath, 'utf8');
    return {
      host,
      port,
      username,
      privateKey,
      passphrase: process.env[`${KEY_PREFIX}DEPLOY_PRIVATE_KEY_PASSPHRASE`]
    };
  }
  const password = getRequiredEnv(`${KEY_PREFIX}DEPLOY_PASSWORD`);
  return { host, port, username, password };
}

// Resolves the local + remote roots for the active --only mode and the
// filter that decides which files inside the local root get uploaded.
//
//   all    — upload dist/.../browser/, write .htaccess at the root.
//   code   — upload dist/.../browser/ minus the assets/ subtree, still
//            writes .htaccess (Angular bundle changes can affect routing).
//   assets — upload only dist/.../browser/assets/ → <remote>/assets/, no
//            .htaccess (assets-only redeploys shouldn't churn that file).
function resolveDeployTargets(remoteRoot) {
  const assetsLocal = path.join(LOCAL_DIR, 'assets');

  if (ONLY === 'assets') {
    return {
      localRoot: assetsLocal,
      remoteRoot: `${remoteRoot}/assets`,
      writeHtaccess: false,
      filter: (filePath, isDirectory) => {
        if (isDirectory) return true;
        return path.basename(filePath) !== '.DS_Store';
      }
    };
  }

  if (ONLY === 'code') {
    return {
      localRoot: LOCAL_DIR,
      remoteRoot,
      writeHtaccess: true,
      filter: (filePath, isDirectory) => {
        // Skip the assets/ subtree entirely (both the directory itself
        // and anything beneath it).
        const rel = path.relative(LOCAL_DIR, filePath);
        const inAssets =
          rel === 'assets' || rel.startsWith('assets' + path.sep);
        if (inAssets) return false;
        if (isDirectory) return true;
        return path.basename(filePath) !== '.DS_Store';
      }
    };
  }

  return {
    localRoot: LOCAL_DIR,
    remoteRoot,
    writeHtaccess: true,
    filter: (filePath, isDirectory) => {
      if (isDirectory) return true;
      return path.basename(filePath) !== '.DS_Store';
    }
  };
}

async function countFiltered(root, filter) {
  let n = 0;
  for await (const file of walk(root)) {
    if (filter(file, false)) n++;
  }
  return n;
}

async function deploy() {
  await build();
  await ensureLocalDir();

  const remoteBase = getRequiredEnv(`${KEY_PREFIX}DEPLOY_REMOTE_DIR`).replace(/\/+$/, '');
  assertRemoteAllowed(remoteBase);
  const targets = resolveDeployTargets(remoteBase);

  if (targets.writeHtaccess) {
    await writeHtaccess();
  }

  if (!existsSync(targets.localRoot)) {
    fail(`Local source not found at ${targets.localRoot}.`);
  }

  const auth = await buildAuthOptions();

  if (DRY_RUN) {
    console.log(`[deploy] env:  --env=${ENV}  ng config: ${NG_CONFIG}`);
    console.log(`[deploy] mode: --only=${ONLY}`);
    console.log(`[deploy] dry run — would connect to ${auth.username}@${auth.host}:${auth.port}`);
    console.log(`[deploy] local root:  ${targets.localRoot}`);
    console.log(`[deploy] remote root: ${targets.remoteRoot}`);
    const count = await countFiltered(targets.localRoot, targets.filter);
    console.log(`[deploy] would upload ${count} files`);
    return;
  }

  const sftp = new SftpClient();
  try {
    console.log(`[deploy] env:  --env=${ENV}  ng config: ${NG_CONFIG}`);
    console.log(`[deploy] mode: --only=${ONLY}`);
    console.log(`[deploy] connecting to ${auth.username}@${auth.host}:${auth.port}…`);
    console.log(`[deploy] remote root: ${targets.remoteRoot}`);
    await sftp.connect(auth);

    console.log(`[deploy] uploading ${targets.localRoot} → ${targets.remoteRoot}`);

    // ssh2-sftp-client's uploadDir mirrors a local directory to a remote
    // directory, creating missing parents. We accept some noise
    // (re-uploads of hashed chunk files) in exchange for simplicity.
    await sftp.uploadDir(targets.localRoot, targets.remoteRoot, {
      useFastput: true,
      filter: targets.filter
    });

    console.log('[deploy] done.');
  } catch (err) {
    fail(`upload failed: ${err.message}`);
  } finally {
    await sftp.end().catch(() => {});
  }
}

deploy().catch((err) => fail(err.message ?? String(err)));
